Repository Laravel-Backpack/theme-tabler, pull requests merged in 2023-07, with the labels that each got.

#93 add styles for DevTools
  resources/assets/css/style.css
Labels: Priority: SHOULD, non breaking change

#101 Fix dark mode
  resources/assets/css/color-adjustments.css
  resources/assets/css/style.css
Labels: Priority: MUST

#106 ColorMode event return the actual color
  resources/views/layouts/partials/light_dark_mode_logic.blade.php
Labels: Priority: SHOULD

#110 Fix dark mode issues
  resources/assets/css/style.css
Labels: Priority: MUST

#109 Multiple menu items get selected if another slug has substring.
  resources/assets/js/tabler.js
Labels: Priority: SHOULD, bug, Size: XS

#123 fix white flick when in dark mode
  resources/views/inc/theme_styles.blade.php
Labels: Priority: SHOULD
