Repository Laravel-Backpack/theme-tabler, pull requests merged in 2023-06, with the labels that each got.

#55 move most widgets to CRUD
  resources/views/widgets/alert.blade.php
  resources/views/widgets/div.blade.php
  resources/views/widgets/inc/wrapper_end.blade.php
  resources/views/widgets/inc/wrapper_start.blade.php
  resources/views/widgets/jumbotron.blade.php
  resources/views/widgets/script.blade.php
  resources/views/widgets/style.blade.php
  resources/views/widgets/view.blade.php
  src/AddonServiceProvider.php
  src/AutomaticServiceProvider.php
Labels: Priority: MUST

#58 [Bug] Remove url helper from config
  config/theme-tabler.php
  src/AddonServiceProvider.php
Labels: Priority: MUST, bug

#78 remove administration keyword from menus
  resources/views/layouts/_horizontal/menu_container.blade.php
  resources/views/layouts/_horizontal_dark/menu_container.blade.php
  resources/views/layouts/_horizontal_overlap/menu_container.blade.php
  resources/views/layouts/_right_vertical/menu_container.blade.php
  resources/views/layouts/_right_vertical_dark/menu_container.blade.php
  resources/views/layouts/_right_vertical_transparent/menu_container.blade.php
  resources/views/layouts/_vertical/menu_container.blade.php
  resources/views/layouts/_vertical_dark/menu_container.blade.php
  resources/views/layouts/_vertical_transparent/menu_container.blade.php
Labels: bug

#60 fix horizontal overlap layout
  config/theme-tabler.php
  resources/assets/css/style.css
  resources/views/layouts/_horizontal_overlap/menu_container.blade.php
  resources/views/layouts/horizontal.blade.php
  resources/views/layouts/horizontal_dark.blade.php
  resources/views/layouts/horizontal_overlap.blade.php
  resources/views/layouts/plain.blade.php
  resources/views/layouts/right_vertical.blade.php
  resources/views/layouts/right_vertical_dark.blade.php
  resources/views/layouts/right_vertical_transparent.blade.php
  resources/views/layouts/vertical.blade.php
  resources/views/layouts/vertical_dark.blade.php
  resources/views/layouts/vertical_transparent.blade.php
  src/AddonServiceProvider.php
Labels: Priority: MUST, Priority: SHOULD, Size: M

#83 make horizontal-overlap the default layout
  config/theme-tabler.php
Labels: Priority: SHOULD, Size: XS

#85 docs publish config
  readme.md
  src/AutomaticServiceProvider.php
Labels: Priority: MUST

#79 add view components for menus
  resources/views/components/menu-dropdown-item.blade.php
  resources/views/components/menu-dropdown.blade.php
  resources/views/components/menu-item.blade.php
  resources/views/components/menu-separator.blade.php
Labels: Priority: MUST, Priority: SHOULD

#82 Fix align on horizontal and 'doubleTopBarInHorizontalLayouts' => false,
  resources/assets/css/style.css
  resources/views/layouts/_horizontal/menu_container.blade.php
  resources/views/layouts/_horizontal_dark/menu_container.blade.php
  resources/views/layouts/_horizontal_overlap/menu_container.blade.php
Labels: Priority: MUST, Priority: SHOULD, bug, Size: S, Size: XS

#86 use ThemeServiceProvider
  src/AddonServiceProvider.php
  src/AutomaticServiceProvider.php
Labels: Priority: MUST, Priority: SHOULD, Size: XS

#61 Feature - System Color Mode
  config/theme-tabler.php
  resources/assets/css/color-adjustments.css
  resources/assets/css/style.css
  resources/views/auth/passwords/email.blade.php
  resources/views/auth/passwords/reset.blade.php
  resources/views/inc/head.blade.php
  resources/views/layouts/auth.blade.php
  resources/views/layouts/partials/light_dark_mode_logic.blade.php
  resources/views/layouts/partials/switch_theme.blade.php
Labels: Priority: COULD, Priority: MUST, Priority: SHOULD

#87 Upgrade Tabler to beta 19
  resources/assets/css/color-adjustments.css
  resources/assets/css/colors.css
  resources/assets/css/style.css
  resources/views/inc/theme_scripts.blade.php
  resources/views/inc/theme_styles.blade.php
  resources/views/layouts/_horizontal/header_container.blade.php
  resources/views/layouts/_horizontal/menu_container.blade.php
  resources/views/layouts/_horizontal_dark/header_container.blade.php
  resources/views/layouts/_horizontal_dark/menu_container.blade.php
  resources/views/layouts/_horizontal_overlap/header_container.blade.php
  resources/views/layouts/_horizontal_overlap/menu_container.blade.php
  resources/views/layouts/_right_vertical/menu_container.blade.php
  resources/views/layouts/_right_vertical/sidebar_content_top.blade.php
  resources/views/layouts/_right_vertical_dark/menu_container.blade.php
  resources/views/layouts/_right_vertical_dark/sidebar_content_top.blade.php
  resources/views/layouts/_right_vertical_transparent/header_container.blade.php
  resources/views/layouts/_right_vertical_transparent/menu_container.blade.php
  resources/views/layouts/_vertical/menu_container.blade.php
  resources/views/layouts/_vertical/sidebar_content_top.blade.php
  resources/views/layouts/_vertical_dark/menu_container.blade.php
  resources/views/layouts/_vertical_dark/sidebar_content_top.blade.php
  resources/views/layouts/_vertical_transparent/menu_container.blade.php
Labels: Priority: MUST, Size: M

#92 Fix classes.body does not exist error
  config/theme-tabler.php
Labels: Priority: MUST
