Repository Laravel-Backpack/theme-tabler, pull requests merged in 2023-08, with the labels that each got.

#117 Add new css style to make line visible on dark mode
  resources/assets/css/style.css
Labels: Priority: MUST, Priority: SHOULD, Size: XS

#126 Fix light title on mobile
  resources/assets/css/style.css
Labels: Priority: MUST, bug, Size: XS

#116 Fix dark mode overlay on elFinder iframe
  resources/assets/css/style.css
Labels: Priority: MUST

#134 Horizontal layout tab title hard to read
  resources/assets/css/style.css
Labels: bug, Size: XS

#133 Progress widgets text color fix
  resources/views/widgets/progress.blade.php
  resources/views/widgets/progress_white.blade.php
Labels: Priority: MUST, bug, Size: XS

#142 add email verification view
  composer.json
  resources/views/auth/verify-email.blade.php
Labels: Priority: MUST
